allowBuilds:
  esbuild: set this to true or false
  msw: set this to true or false
  sharp: set this to true or false
  workerd: set this to true or false
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - msw
  - sharp
  - workerd
