allowBuilds:
  canvas: set this to true or false
  esbuild: false
  msw: false
  sharp: false
  workerd: false
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - msw
  - sharp
  - workerd
