/**
 * Website Auditor — Cursor helpers.
 *
 * Cursor accepts prompts via two deep links:
 *   cursor://anysphere.cursor.com/new?prompt=<urlencoded>   (opens new editor)
 *   cursor://anysphere.cursor.com/open?prompt=<urlencoded>  (uses focused editor)
 *
 * The browser's OS dispatches `cursor://` to the Cursor desktop app if it's
 * installed; otherwise the click is a no-op. We always render the link so
 * power users get the "click and land in Cursor" flow; everyone else can
 * still hit "Copy" and paste by hand.
 *
 * The model already produces paste-ready prompts per finding; this module
 * only adds shape-conversion (deep-link wrapping, batched Markdown export).
 */

export interface FindingLike {
  id: string;
  title: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  dimension: string;
  cursorPrompt: string;
}

/** Build a Cursor deep link for a single prompt. */
export function cursorDeepLink(prompt: string): string {
  return `cursor://anysphere.cursor.com/new?prompt=${encodeURIComponent(prompt)}`;
}

/** Severity badge for display (used in batched output and cards). */
export function severityBadge(
  s: 'critical' | 'high' | 'medium' | 'low'
): string {
  return `[${s.toUpperCase()}]`;
}

export interface BatchOptions {
  url: string;
  locale: 'en' | 'zh';
  /** Optional sorted list — if provided, output the priorities only. */
  onlyIds?: string[];
}

/**
 * Wrap multiple findings into a single Markdown document for "Copy all" /
 * paste-to-Slack / paste-to-Notion buttons. Each finding gets its own
 * fenced code block so the user can lift them out individually later.
 */
export function batchAsMarkdown(
  findings: FindingLike[],
  options: BatchOptions
): string {
  const { url, locale, onlyIds } = options;
  const list = onlyIds
    ? findings.filter((f) => onlyIds.includes(f.id))
    : findings;
  const heading =
    locale === 'zh'
      ? `# 网站修复清单\n\n由 kimik3 生成 — 每个 \`\`\` 代码块都可以直接粘贴到 Cursor。`
      : `# Website Audit Fixes\n\nGenerated by kimik3 — each code block is paste-ready into Cursor.`;
  const footer =
    locale === 'zh'
      ? `\n---\n\n审计目标: ${url}\n`
      : `\n---\n\nAudited: ${url}\n`;
  const body = list
    .map((f, i) => {
      const badge = severityBadge(f.severity);
      return `## ${i + 1}. ${badge} ${f.title}\n\n**${f.dimension}** · \`${f.id}\`\n\n\`\`\`\n${f.cursorPrompt}\n\`\`\`\n`;
    })
    .join('\n');
  return `${heading}\n\n${body}${footer}`;
}

/**
 * Re-format a finding's prompt through our template to enforce consistency.
 * The LLM produces its own version but admin-style overrides are possible
 * (e.g. "always include the URL in the header"). V1 just trims.
 */
export function normalizeCursorPrompt(raw: string): string {
  return raw.replace(/\r\n/g, '\n').trim();
}
